### ISSUE TITLE
/impound & Target Impound

### ISSUE THREAD

**Issue by ahmoge** [zf-labo/ox_compat#3]
hello got some error when i try to /impound from policejob of [i-kulgu](https://github.com/i-kulgu/qb-policejob)
**this one on /impound**
![image](https://github.com/zf-labo/ox_compat/assets/121356172/48d93c77-e23a-4830-bf66-0f47a07a8efb)
**and for target**
![image](https://github.com/zf-labo/ox_compat/assets/121356172/8a28522c-0517-4462-8f10-e4cc310170ed)
still using qb-target atm.

**Comment by zf-development** [comment]
It been fixed a day later.
