### ISSUE TITLE
Error when clicking "Preview property loaf_housing"

### ISSUE THREAD

**Issue by onscripts** [zf-labo/ox_compat#4]
![image](https://github.com/zf-labo/ox_compat/assets/94694368/031c7994-b540-4732-b5ac-3a52ab37ccc8)

Hello, I get this error when I click on the menu.
![image](https://github.com/zf-labo/ox_compat/assets/94694368/33d94172-df8c-4750-80d9-c7ba6be01a85)

**Comment by zf-development** [comment]
Fixed.
