### ISSUE TITLE
target error

### ISSUE THREAD

**Issue by Llama-Palooza** [zf-labo/ox_compat#6]
While using the option to convert qb-target to ox_target, I get this error while a script is starting up. I'm assuming ox-target doesn't have the GetPeds export.
![image](https://github.com/zf-labo/ox_compat/assets/124511433/dfa08574-6583-4c10-b344-2ce2fc62a371)

**Comment by CoZmoTheGod** [comment]
Would love to see this resolved so I can use ox with r14-objects as well!

**Comment by Llama-Palooza** [comment]
Likewise. Would be nice if this was a 100% replacement but as of right now, it won't work in qb servers that use scripts that call for exports ox-target doesn't have.

**Comment by zf-development** [comment]
I added the export support for GetPeds.
